### ISSUE TITLE
Invalid Isoformat String

### ISSUE THREAD

**Issue by crowimu** [jmazzahacks/byteforge-coinmarketcap#1]
Hi! 
When I ry the demo code I get the following Error:

```
Traceback (most recent call last):
  File "/home/pi/wetter/cmc_api_test.py", line 9, in <module>
    token_states = coinmarketcap.listings_latest(sort_by=SortOption.MARKET_CAP, limit=5)
  File "/home/pi/.local/lib/python3.9/site-packages/coinmarketcap/core.py", line 83, in listings_latest
    return _listings_latest(self, sort_by, sort_dir, start, limit, convert, aux_fields, filters)
  File "/home/pi/.local/lib/python3.9/site-packages/coinmarketcap/v1/cryptocurrency/listings/latest.py", line 59, in _listings_latest
    token_states = [TokenState.from_dict(token) for token in response['data']]
  File "/home/pi/.local/lib/python3.9/site-packages/coinmarketcap/v1/cryptocurrency/listings/latest.py", line 59, in <listcomp>
    token_states = [TokenState.from_dict(token) for token in response['data']]
  File "/home/pi/.local/lib/python3.9/site-packages/coinmarketcap/types/token_state.py", line 100, in from_dict
    quote_map[currency] = Quote.from_dict(currency, dct_quote_data)
  File "/home/pi/.local/lib/python3.9/site-packages/coinmarketcap/types/token_state.py", line 57, in from_dict
    last_updated = datetime.datetime.fromisoformat(last_updated_str)
ValueError: Invalid isoformat string: '2024-03-28T13:22:00.000Z'
```
The code I used is quite simple:

from coinmarketcap import Market
from coinmarketcap import SortOption

API_KEY = 'my-api-key'
coinmarketcap = Market(api_key=API_KEY)

token_states = coinmarketcap.listings_latest(sort_by=SortOption.MARKET_CAP, limit=5)

for token in tokens:
    print(token.name, token.symbol, token.quote_map['USD'].price)

Can you help?

**Comment by jmazzahacks** [comment]
I just used a newer version that should have more reliable date parsing to address this, can you give that a try?

https://pypi.org/project/byteforge-coinmarketcap/1.1/

**Comment by crowimu** [comment]
> I just used a newer version that should have more reliable date parsing to address this, can you give that a try?
> 
> https://pypi.org/manage/project/byteforge-coinmarketcap/release/1.1/

Thanks, but I get the error "You do not have permission to view this page" on pypi.org  :(

**Comment by jmazzahacks** [comment]
Sorry, that's an admin only link.  In theory you just need to update to the latest version of the library

pip install --upgrade byteforge-coinmarketcap

**Comment by crowimu** [comment]
Now I get the following exception:
```
" File "/home/pi/.local/lib/python3.9/site-packages/coinmarketcap/core.py", line 62, in _request
    raise Exception(f"Server returned {response_object.status_code} - {response_object.text}")
Exception: Server returned 400 - {"status":{"timestamp":"2024-04-02T09:20:27.442Z","error_code":400,"error_message":"\"Your plan is limited to 1 convert options","elapsed":0,"credit_count":0,"notice":null}}"

```

**Comment by jmazzahacks** [comment]
That’s an API restriction, for example if you are just using their free tier you can only do one conversion

So this code wouldn’t work unless you upgraded to Hobbyist

tokens = coinmarketcap.listings_latest(sort_by=SortOption.MARKET_CAP, limit=5, convert=['USD', 'BTC'])

But this would:

tokens = coinmarketcap.listings_latest(sort_by=SortOption.MARKET_CAP, limit=5, convert=['USD'])

I’ll update the docs to make this more clear.

**Comment by crowimu** [comment]
Sorry my bad, thank you for the hint :) 
Now it works. Great!
